[package]
name = "png-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deflate = "1.0.0"
crc = "3.0.0"
iron = "0.6.1"